# Exercise 1.02 — Indexing, Slicing, Splitting, and Iterating

This notebook uses `normal_distribution_splittable.csv`, a 24 × 9 NumPy dataset.

In [1]:
import numpy as np
from pathlib import Path

data_path = Path("..") / "Datasets" / "normal_distribution_splittable.csv"
dataset = np.genfromtxt(data_path, delimiter=",")
print("Dataset shape:", dataset.shape)
dataset

Dataset shape: (24, 9)


array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189,
        101.34745901],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942,
         93.87155456],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286,
        107.22482426],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803,
        103.40412146],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732,
         96.10020311],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416,
         97.62787811],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.4649

## Indexing

In [2]:
# Mean of the second row
second_row = dataset[1]
np.mean(second_row)

np.float64(96.90038836444445)

In [3]:
# Mean of the last row using reverse indexing
last_row = dataset[-1]
np.mean(last_row)

np.float64(100.18096645222221)

In [4]:
# First value of the first row
first_value_first_row = dataset[0][0]
first_value_first_row

np.float64(99.14931546)

In [5]:
# Last value of the second-last row
last_value_second_last_row = dataset[-2, -1]
last_value_second_last_row

np.float64(101.2226037)

## Slicing

In [6]:
# 2 × 2 intersection beginning at the second row and second column
subsection_2x2 = dataset[1:3, 1:3]
subsection_2x2

array([[97.10439252, 99.32066924],
       [95.17750125, 90.93318132]])

In [7]:
# Every other element of the fifth row
every_other_fifth_row = dataset[4, ::2]
every_other_fifth_row

array([101.20862522, 100.28690912,  93.37126331, 100.79478953,
        96.10020311])

In [8]:
# Reverse the final row
reversed_last_row = dataset[-1, ::-1]
reversed_last_row

array([106.89005002, 100.07721494, 106.05042487,  98.75108352,
        93.97853495,  97.62787811, 104.51786419,  99.62387832,
        94.11176915])

## Splitting

In [9]:
# Split horizontally into three equal parts
horizontal_splits = np.hsplit(dataset, 3)
print([part.shape for part in horizontal_splits])

[(24, 3), (24, 3), (24, 3)]


In [10]:
# Split the first horizontal part vertically into two equal parts
vertical_splits = np.vsplit(horizontal_splits[0], 2)
print([part.shape for part in vertical_splits])

[(12, 3), (12, 3)]


In [11]:
# Compare the original and subset shapes
print("Dataset:", dataset.shape)
print("Subset:", vertical_splits[0].shape)

Dataset: (24, 9)
Subset: (12, 3)


## Iterating

In [12]:
# Iterate over every value; show a preview and the total count.
values = []
for value in np.nditer(dataset):
    values.append(float(value))
print("First 12 values:", values[:12])
print("Values visited:", len(values))

First 12 values: [99.14931546, 104.03852715, 107.43534677, 97.85230675, 98.74986914, 98.80833412, 96.81964892, 98.56783189, 101.34745901, 92.02628776, 97.10439252, 99.32066924]
Values visited: 216


In [13]:
# Iterate with row-and-column indices using ndenumerate
indexed_values = []
for index, value in np.ndenumerate(dataset):
    indexed_values.append((index, float(value)))
print("First 12 indexed values:", indexed_values[:12])
print("Indexed values visited:", len(indexed_values))

First 12 indexed values: [((0, 0), 99.14931546), ((0, 1), 104.03852715), ((0, 2), 107.43534677), ((0, 3), 97.85230675), ((0, 4), 98.74986914), ((0, 5), 98.80833412), ((0, 6), 96.81964892), ((0, 7), 98.56783189), ((0, 8), 101.34745901), ((1, 0), 92.02628776), ((1, 1), 97.10439252), ((1, 2), 99.32066924)]
Indexed values visited: 216
