# Activity 1.01 — Mean, Median, Variance, and Standard Deviation

This activity consolidates the NumPy operations from Exercise 1.01 using `normal_distribution.csv`.

In [1]:
# Import NumPy and load the dataset
import numpy as np
from pathlib import Path

data_path = Path("..") / "Datasets" / "normal_distribution.csv"
dataset = np.genfromtxt(data_path, delimiter=",")
print("Dataset shape:", dataset.shape)

Dataset shape: (24, 8)


In [2]:
# Print a subset of the first two rows
dataset[0:2]

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942]])

## Mean

In [3]:
# Mean of the third row
a_mean_third_row = np.mean(dataset[2])
a_mean_third_row

np.float64(100.20466135250001)

In [4]:
# Mean of the last column
a_mean_last_column = np.mean(dataset[:, -1])
a_mean_last_column

np.float64(100.4404927375)

In [5]:
# Mean of the first three rows and first three columns
a_mean_submatrix = np.mean(dataset[0:3, 0:3])
a_mean_submatrix

np.float64(97.87197312333333)

## Median

In [6]:
# Median of the last row
a_median_last_row = np.median(dataset[-1])
a_median_last_row

np.float64(99.18748092)

In [7]:
# Median of the last three columns
a_median_last_columns = np.median(dataset[:, -3:])
a_median_last_columns

np.float64(99.47332349999999)

In [8]:
# Median of each row
a_median_each_row = np.median(dataset, axis=1)
a_median_each_row

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

## Variance and standard deviation

In [9]:
# Variance of each column
a_variance_each_column = np.var(dataset, axis=0)
a_variance_each_column

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [10]:
# Variance of the last two rows and first two columns
a_variance_submatrix = np.var(dataset[-2:, :2])
a_variance_submatrix

np.float64(4.674691991769191)

In [11]:
# Standard deviation for the complete dataset
a_standard_deviation = np.std(dataset)
a_standard_deviation

np.float64(4.838197554269257)