# Exercise 1.03 — Filtering, Sorting, Combining, and Reshaping

This notebook applies advanced NumPy operations to `normal_distribution_splittable.csv`.

In [1]:
import numpy as np
from pathlib import Path

data_path = Path("..") / "Datasets" / "normal_distribution_splittable.csv"
dataset = np.genfromtxt(data_path, delimiter=",")
print("Dataset shape:", dataset.shape)
dataset

Dataset shape: (24, 9)


array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189,
        101.34745901],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942,
         93.87155456],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286,
        107.22482426],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803,
        103.40412146],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732,
         96.10020311],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416,
         97.62787811],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.4649

## Filtering

In [2]:
# Values greater than 105
values_greater_105 = dataset[dataset > 105]
print("Count:", values_greater_105.size)
values_greater_105

Count: 42


array([107.43534677, 105.7197853 , 110.18889465, 105.95297652,
       106.54654286, 107.22482426, 113.42090475, 105.48508838,
       106.1472841 , 105.85269352, 108.57980357, 106.71751618,
       106.39798503, 106.83273763, 106.47551845, 105.30350449,
       106.03868807, 110.44484313, 106.6471081 , 105.0320535 ,
       107.02874163, 105.07475277, 106.57364584, 107.22482426,
       107.19119932, 108.09423367, 109.40523174, 106.11454989,
       106.57052697, 105.13668343, 105.37011896, 110.44484313,
       105.86078488, 106.89005002, 106.57364584, 107.40064604,
       106.38276709, 106.46476468, 110.43976681, 105.02389857,
       106.05042487, 106.89005002])

In [3]:
# Values strictly between 90 and 95
values_between_90_95 = np.extract((dataset > 90) & (dataset < 95), dataset)
print("Count:", values_between_90_95.size)
values_between_90_95

Count: 30


array([92.02628776, 92.9267508 , 92.65657752, 93.87155456, 90.93318132,
       91.37294597, 91.6604946 , 93.37126331, 94.20019732, 93.24376389,
       94.35373179, 92.5748759 , 91.37294597, 92.87730812, 93.87155456,
       92.75048583, 93.97853495, 91.32093303, 92.0108226 , 93.18884302,
       93.83969256, 94.5081787 , 94.59300658, 93.04610867, 91.6779221 ,
       91.37294597, 94.76253572, 94.57421727, 94.11176915, 93.97853495])

In [4]:
# Indices of values whose distance from 100 is less than 1
rows, columns = np.where(np.abs(dataset - 100) < 1)
one_away_indices = list(zip(rows.tolist(), columns.tolist()))
print("Matching positions:", len(one_away_indices))
one_away_indices

Matching positions: 33


[(0, 0),
 (1, 2),
 (3, 1),
 (3, 2),
 (4, 2),
 (4, 6),
 (6, 3),
 (6, 8),
 (8, 5),
 (9, 8),
 (10, 1),
 (10, 3),
 (10, 5),
 (12, 8),
 (13, 0),
 (13, 4),
 (13, 7),
 (14, 3),
 (14, 5),
 (15, 8),
 (16, 1),
 (16, 6),
 (17, 2),
 (17, 3),
 (18, 7),
 (18, 8),
 (20, 4),
 (21, 0),
 (21, 4),
 (21, 5),
 (22, 2),
 (23, 1),
 (23, 7)]

## Sorting

In [5]:
# Sort each row (the last axis by default)
row_sorted = np.sort(dataset)
row_sorted

array([[ 96.81964892,  97.85230675,  98.56783189,  98.74986914,
         98.80833412,  99.14931546, 101.34745901, 104.03852715,
        107.43534677],
       [ 92.02628776,  92.65657752,  92.9267508 ,  93.87155456,
         97.10439252,  97.24584816,  99.32066924, 101.23162942,
        105.7197853 ],
       [ 90.93318132,  95.17750125,  95.66253664,  98.37481387,
         98.80084371, 105.95297652, 106.54654286, 107.22482426,
        110.18889465],
       [ 91.37294597,  91.6604946 ,  95.08715803, 100.40118279,
        100.96781394, 103.40412146, 105.48508838, 106.1472841 ,
        113.42090475],
       [ 93.37126331,  94.20019732,  96.10020311, 100.28690912,
        100.79478953, 101.20862522, 103.5730309 , 105.85269352,
        108.57980357],
       [ 89.03452725,  93.24376389,  96.2832753 ,  97.24130034,
         97.62787811,  98.29687616, 101.13442416, 102.80387079,
        104.60344836],
       [ 94.35373179,  95.46493436,  98.45723272, 100.07721494,
        100.72418901, 102.9758

In [6]:
# Sort values by column
column_sorted = np.sort(dataset, axis=0)
column_sorted

array([[ 91.37294597,  88.80221141,  90.93318132,  93.18884302,
         85.98839623,  91.6604946 ,  91.32093303,  92.5748759 ,
         91.37294597],
       [ 92.02628776,  91.6779221 ,  93.24376389,  94.59300658,
         89.03452725,  92.65657752,  93.04610867,  94.20019732,
         91.37294597],
       [ 94.11176915,  92.0108226 ,  93.83969256,  96.74630281,
         92.75048583,  95.19184343,  94.35373179,  94.76253572,
         93.87155456],
       [ 95.65982034,  92.87730812,  94.5081787 ,  97.24130034,
         92.9267508 ,  95.46493436,  96.50342927,  95.08715803,
         93.97853495],
       [ 95.66253664,  93.87155456,  97.75887636,  97.24584816,
         93.37126331,  95.62359311,  96.81964892,  95.85284217,
         95.19184343],
       [ 96.02548256,  94.57421727,  98.45723272,  97.62787811,
         93.97853495,  96.2832753 ,  96.89244283,  97.59572169,
         96.10020311],
       [ 96.10020311,  95.17750125,  99.32066924,  97.65393524,
         95.93799169,  96.3462

In [7]:
# Use argsort and fancy indexing to sort the first row
index_sorted = np.argsort(dataset[0])
sorted_first_row = dataset[0][index_sorted]
print("Sorted indices:", index_sorted)
sorted_first_row

Sorted indices: [6 3 7 4 5 0 8 1 2]


array([ 96.81964892,  97.85230675,  98.56783189,  98.74986914,
        98.80833412,  99.14931546, 101.34745901, 104.03852715,
       107.43534677])

## Combining

In [8]:
# Split into thirds, then split the first third into two row blocks
thirds = np.hsplit(dataset, 3)
halved_first = np.vsplit(thirds[0], 2)
print("Third shapes:", [part.shape for part in thirds])
print("First-third halves:", [part.shape for part in halved_first])

Third shapes: [(24, 3), (24, 3), (24, 3)]
First-third halves: [(12, 3), (12, 3)]


In [9]:
# Vertically combine the two halves of the first third
first_column_block = np.vstack([halved_first[0], halved_first[1]])
first_column_block

array([[ 99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  97.10439252,  99.32066924],
       [ 95.66253664,  95.17750125,  90.93318132],
       [ 91.37294597, 100.96781394, 100.40118279],
       [101.20862522, 103.5730309 , 100.28690912],
       [102.80387079,  98.29687616,  93.24376389],
       [106.71751618, 102.97585605,  98.45723272],
       [ 96.02548256, 102.82360856, 106.47551845],
       [105.30350449,  92.87730812, 103.19258339],
       [110.44484313,  93.87155456, 101.5363647 ],
       [101.3514185 , 100.37372248, 106.6471081 ],
       [ 97.21315663, 107.02874163, 102.17642112],
       [ 95.65982034, 107.22482426, 107.19119932],
       [100.39303522,  92.0108226 ,  97.75887636],
       [103.1521596 , 109.40523174,  93.83969256],
       [106.11454989,  88.80221141,  94.5081787 ],
       [ 96.78266211,  99.84251605, 104.03478031],
       [101.86186193, 103.61720152,  99.57859892],
       [ 97.49594839,  96.59385486, 104.63817694],
       [ 96.76814836,  91.67792

In [10]:
# Add the second third horizontally
first_second_block = np.hstack([first_column_block, thirds[1]])
print("Shape after adding second block:", first_second_block.shape)
first_second_block

Shape after adding second block: (24, 6)


array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 ],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 ],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.74767493],
       [105.30350449,  92.87730812, 103.19258339, 104.40518318,
        101.29326772, 100.85447132],
       [110.44484313,  93.87155456, 101.5363647 ,  97.65393524,
         92.75048583, 101.7

In [11]:
# Add the final third horizontally to reconstruct the full dataset
full_data = np.hstack([first_second_block, thirds[2]])
print("Reconstructed shape:", full_data.shape)
print("Reconstruction matches original:", np.array_equal(full_data, dataset))

Reconstructed shape: (24, 9)
Reconstruction matches original: True


## Reshaping

In [12]:
# Reshape the dataset into one row
single_list = np.reshape(dataset, (1, -1))
print("Shape:", single_list.shape)
single_list

Shape: (1, 216)


array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189,
        101.34745901,  92.02628776,  97.10439252,  99.32066924,
         97.24584816,  92.9267508 ,  92.65657752, 105.7197853 ,
        101.23162942,  93.87155456,  95.66253664,  95.17750125,
         90.93318132, 110.18889465,  98.80084371, 105.95297652,
         98.37481387, 106.54654286, 107.22482426,  91.37294597,
        100.96781394, 100.40118279, 113.42090475, 105.48508838,
         91.6604946 , 106.1472841 ,  95.08715803, 103.40412146,
        101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732,
         96.10020311, 102.80387079,  98.29687616,  93.24376389,
         97.24130034,  89.03452725,  96.2832753 , 104.60344836,
        101.13442416,  97.62787811, 106.71751618, 102.97585605,
         98.45723272, 100.72418901, 106.39798503,  95.46493436,
         94.35373179, 106.83273763, 100.

In [13]:
# Reshape the dataset into two columns; NumPy infers the row count
two_column_dataset = dataset.reshape(-1, 2)
print("Shape:", two_column_dataset.shape)
two_column_dataset

Shape: (108, 2)


array([[ 99.14931546, 104.03852715],
       [107.43534677,  97.85230675],
       [ 98.74986914,  98.80833412],
       [ 96.81964892,  98.56783189],
       [101.34745901,  92.02628776],
       [ 97.10439252,  99.32066924],
       [ 97.24584816,  92.9267508 ],
       [ 92.65657752, 105.7197853 ],
       [101.23162942,  93.87155456],
       [ 95.66253664,  95.17750125],
       [ 90.93318132, 110.18889465],
       [ 98.80084371, 105.95297652],
       [ 98.37481387, 106.54654286],
       [107.22482426,  91.37294597],
       [100.96781394, 100.40118279],
       [113.42090475, 105.48508838],
       [ 91.6604946 , 106.1472841 ],
       [ 95.08715803, 103.40412146],
       [101.20862522, 103.5730309 ],
       [100.28690912, 105.85269352],
       [ 93.37126331, 108.57980357],
       [100.79478953,  94.20019732],
       [ 96.10020311, 102.80387079],
       [ 98.29687616,  93.24376389],
       [ 97.24130034,  89.03452725],
       [ 96.2832753 , 104.60344836],
       [101.13442416,  97.62787811],
 